apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-controller
  namespace: default
  labels:
    load-type: critical
    energy-priority: high
    c2g/managed: "true"
    app: storage-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: storage-controller
  template:
    metadata:
      labels:
        load-type: critical
        energy-priority: high
        c2g/managed: "true"
        app: storage-controller
      annotations:
        c2g/power-per-replica-kw: "1"
        c2g/idle-power-kw: "200"
        c2g/shed-threshold-mwh: "999999"
        c2g/workload-type: storage
        c2g/criticality: critical
        c2g/max-replicas: "3"
    spec:
      containers:
        - name: controller
          image: busybox
          command: ["sh", "-c", "while true; do sleep 3600; done"]
          resources:
            requests:
              cpu: "2"
              memory: "8Gi"
            limits:
              cpu: "2"
              memory: "8Gi"
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "2"]
      terminationGracePeriodSeconds: 30
